version: "3.8"
services:
  zookeeper:
  image: bitnami/zookeeper:3.8
  environment:
  - ALLOW_ANONYMOUS_LOGIN=yes
  ports:
  - "2181:2181"


  kafka:
    image: bitnami/kafka:latest
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_LISTENERS=PLAINTEXT://:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
    - "9092:9092"
    depends_on:
    - zookeeper


  postgres_auth:
    image: postgres:15
    environment:
    POSTGRES_USER: auth
    POSTGRES_PASSWORD: authpass
    POSTGRES_DB: authdb
    ports:
    - "5432:5432"
    volumes:
    - pg_auth_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    ports:
    - "6379:6379"


  auth-service:
    build: ./services/auth-service
    depends_on:
    - postgres_auth
    - kafka
    - redis
    environment:
    - DATABASE_URL=postgresql+asyncpg://auth:authpass@postgres_auth:5432/authdb
    - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    - JWT_SECRET=replace_with_secure_secret
    ports:
    - "8001:8000"


  user-service:
    build: ./services/user-service
    depends_on:
    - kafka
    - postgres_auth
    environment:
    - DATABASE_URL=postgresql+asyncpg://auth:authpass@postgres_auth:5432/authdb
    - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
    - "8003:8000"


  notification-service:
    build: ./services/notification-service
    depends_on:
    - kafka
    environment:
    - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    - SMTP_HOST=smtp.example.com
    ports:
    - "8002:8000"


volumes:
  pg_auth_data: